version: '3.8'

services:
  mongo:
    image: mongo
    container_name: patna-metro-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: .
    container_name: patna-metro-backend
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/patnametro

volumes:
  mongo_data:
